name: Install P12 Certificate

on:
  workflow_dispatch:

jobs:          
  import:
    runs-on: macos-latest
    
    steps:
    - uses: Apple-Actions/import-codesign-certs@v2
      with:
        p12-file-base64: ${{ secrets.P12 }}
        p12-password: ${{ secrets.P12_PASSWORD }}
