name: Install P12 Certificate

on:
  workflow_dispatch:

jobs:          
  import:
    runs-on: macos-latest
    
    steps:
    - run: |
        security create-keychain -p ${{ secrets.KEYCHAIN_PASSWORD }} tmp.keychain
        security set-keychain-settings -lut 21600 tmp.keychain
