name: Install P12 Certificate

on:
  workflow_dispatch:

jobs:          
  import:
    runs-on: macos-latest
    
    steps:
    - run: |
        echo ${{ secrets.P12 }} | base64 --decode > certificate.p12
        shasum -a 256 certificate.p12
          
    - uses: Apple-Actions/import-codesign-certs@v2
      with:
        p12-file-base64: ${{ secrets.P12 }}
        p12-password: ${{ secrets.P12_PASSWORD }}
