name: iOS Build Lab

on:
  workflow_dispatch: {}

jobs:
  unity-build:
    name: Unity Build
    runs-on: macos-latest

    steps:
      - name: Download Xcode Project
        uses: actions/download-artifact@v4
        with:
          name: Build-iOS
          path: build/iOS

      - name: Build and Export IPA
        run: |          
          xcodebuild -project build/iOS/iOS/Unity-iPhone.xcodeproj \
                     -scheme Unity-iPhone \
                     -sdk iphoneos \
                     -configuration Release \
                     build
                     
          xcodebuild archive -project build/iOS/Unity-iPhone.xcodeproj \
                             -scheme Unity-iPhone \
                             -sdk iphoneos \
                             -configuration Release \
                             -archivePath build/iOS/Unity-iPhone.xcarchive
                             
          xcodebuild -exportArchive \
                     -archivePath build/iOS/Unity-iPhone.xcarchive \
                     -exportOptionsPlist ExportOptions.plist \
                     -exportPath build/iOS/app.ipa

      - name: Upload IPA to App Store Connect
        run: |
          xcrun altool --upload-app -f build/iOS/app.ipa \
                       -u ${{ secrets.APPLE_ID }} \
                       -p ${{ secrets.APP_SPECIFIC_PASSWORD }} \
                       --type ios
