name: iOS Build Lab

on:
  workflow_dispatch: {}

jobs:
  unity-build:
    name: Unity Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cache Library
        uses: actions/cache@v3
        with:
          path: Library
          key: ${{ runner.os }}-iOS-library-${{ hashFiles('**/Library/*') }}
          restore-keys: |
            ${{ runner.os }}-iOS-library-
      - name: Build Project
        uses: game-ci/unity-builder@v4
        env:
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
        with:
          unityVersion: '2022.3.10f1'
          targetPlatform: iOS

      - name: Upload Build
        uses: actions/upload-artifact@v4
        with:
          name: Build-iOS
          path: build/iOS
          
  iOS-build:
    name: Generate IPA
    runs-on: macos-latest
    needs: unity-build

    steps:
      - name: Download Xcode Project
        uses: actions/download-artifact@v4
        with:
          name: Build-iOS
          path: build/iOS

      - name: Create ExportOptions.plist
        run: |
          echo '<?xml version="1.0" encoding="UTF-8"?><!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd"><plist version="1.0"><dict><key>method</key><string>app-store</string><key>teamID</key><string>ZGQ36244W3</string><key>uploadSymbols</key><true/><key>uploadBitcode</key><true/><key>compileBitcode</key><true/></dict></plist>' > ExportOptions.plist

      - name: Create Provisioning Profile
        run: |
          mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
          echo -n ${{ secrets.PROVISIONING_PROFILE }} | base64 -d > ~/Library/MobileDevice/Provisioning\ Profiles/profile.mobileprovision

      - name: Import Certificates
        uses: Apple-Actions/import-codesign-certs@v1
        with:
          p12-file-base64: ${{ secrets.P12 }}
          p12-password: ${{ secrets.P12_PASSWORD }}

      - name: Build Project
        run: |          
          xcodebuild -project build/iOS/iOS/Unity-iPhone.xcodeproj \
                     -scheme Unity-iPhone \
                     -sdk iphoneos \
                     -configuration Release \
                     build

      - name: Archive Project
        run: |                        
          xcodebuild archive -project build/iOS/Unity-iPhone.xcodeproj \
                             -scheme Unity-iPhone \
                             -sdk iphoneos \
                             -configuration Release \
                             -archivePath build/iOS/Unity-iPhone.xcarchive

      - name: Export IPA
        run: |   
          xcodebuild -exportArchive \
                     -archivePath build/iOS/Unity-iPhone.xcarchive \
                     -exportOptionsPlist ExportOptions.plist \
                     -exportPath build/iOS/app.ipa

      - name: Upload IPA to App Store Connect
        run: |
          xcrun altool --upload-app -f build/iOS/app.ipa \
                       -u ${{ secrets.APPLE_ID }} \
                       -p ${{ secrets.APP_SPECIFIC_PASSWORD }} \
                       --type ios
