name: Unity WebGL Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  buildForAllSupportedPlatforms:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cache Library
        uses: actions/cache@v3
        with:
          path: Library
          key: ${{ runner.os }}-${{ matrix.targetPlatform }}-library-${{ hashFiles('**/Library/*') }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.targetPlatform }}-library-

      - name: Build Project
        uses: game-ci/unity-builder@v4
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
        with:
          unityVersion: '2022.3.10f1'
          targetPlatform: WebGL

      - name: Upload Build
        uses: actions/upload-artifact@v3
        with:
          name: Build-WebGL
          path: build/WebGL

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/WebGL/WebGL
